# Copyright Strimzi authors.
# License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
name: Node

on: [pull_request]

jobs:
  build-master:
    runs-on: ubuntu-latest
    name: Get master bundle size
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Set report output
        run: echo "::set-output name=master_report::$(cat generated/bundle-analyser/report.json)"

  build-current:
    runs-on: ubuntu-latest
    name: Build and Test
    needs: build-master
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Caluclate bundle size
        id: bundle
        uses: ./.github/actions/bundle
      - name: Test
        run: npm run test
      - name: Coverage report
        id: coverage
        if: ${{ always() }}
        uses: ./.github/actions/coverage-report
      - name: Comment on PR
        if: ${{ always() }}
        uses: ./.github/actions/commenter
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUNDLE_SIZE: ${{ steps.bundle.outputs.bundle_size }}
          TEST_COVERAGE: ${{ steps.coverage.outputs.test_coverage }}

  lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm ci
      - name: Lint all files
        run: npm run lint

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: run tests
        run: npm run test:e2e:closed
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: failures
          path: failure_output
